version: '2'
services:
  mysql:
    build: mysql/.
    environment:
      - MYSQL_ROOT_PASSWORD=lkjhlkjh
      - MYSQL_DATABASE=empty_portal  
  webapp:
    build: .
    ports:
      - 8081:80
    depends_on:
      - mysql





    
